### ISSUE TITLE
Version 4.0 Download Links

### ISSUE THREAD

**Issue by arabanal** [CCALI/drupal7-a2j#8]
Links to the 4.0 and 4.1.1. downloads do not work: http://a2jauthor.org/content/download-a2j-author-40. 

Also, the links should be featured on the homepage as well to make them easier to find for those downloading past versions.

**Comment by sgoshorn** [comment]
Any links referencing version 4 can be accessed by using old.a2jauthor.org instead of www.a2jauthor.org. So replace link http://www.a2jauthor.org/drupal/?q=system/files&file=A2JAuthor_Installer_400_2010-12-16.exe with http://old.a2jauthor.org/drupal/?q=system/files&file=A2JAuthor_Installer_400_2010-12-16.exe

**Comment by emasters** [comment]
@sgoshorn @arabanal Will we need links to A2J Author 4 on the new site?

**Comment by arabanal** [comment]
We will need links to 4 on the new site until 5.0 has been fully integrated onto the LHI national server.  4.0 links though do not need to be featured content.
